### ISSUE TITLE
Please explain the difference between installing npm packages globally and what not

### ISSUE THREAD

**Issue by jasonc1** [chinkevin25/full-stack-demo#1]
> As we're developing our server, we can take advantage of nodemon. If nodemon has not been installed yet, install it globally by running npm install -g nodemon. We can then start the server in development mode with nodemon server/server.js.

You mention -D, -S, -G and probs more stuff, but it would be great if you explained why and what the differences are :)

**Comment by justinpchen94** [comment]
For example, you could include in your `1-create-server` branch README:

# Launching the server
Now that we have created the most basic server, we can launch the server by using:
`node <filePath>` or in this case `node server/server.js` if you are in the root directory.

Running the server in this manner, however, has some limitations, namely we will need to quit and restart the server everytime we make changes. To avoid this as we're developing, we can take advantage of `nodemon`, which functions similarly to the `node` command but will watch for changes and automatically restart the application whenever we save.

**Comment by chinkevin25** [comment]
Added comments to those sections.
